# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decrees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('federal', 'federal'), ('regional', 'regional')], max_length=51),
        ),
    ]
